### ISSUE TITLE
forever-monitor logs 

### ISSUE THREAD

**Issue by fithwith** [foreverjs/forever-monitor#101]
I have two following files, I tried 2 things:
-wrinting the logs in files using logFile, outFile and errFile options.
-catching stdout and stderr event .
==>and no one of them worked for me.

//////////////////////////////////////////////////////////////////////////////////////////////////Main.js
  var forever = require('forever-monitor');
  var child = new (forever.Monitor)('./Child.js', {
    'logFile': './log',
    'outFile': './out',
    'errFile': './err'
  });
  child.on('exit', function () {console.log('Exit');});
  child.on('start', function () {console.log('Start');});
  child.on('stdout', function (data) {console.log(data);});
  child.on('stderr', function (data) {console.log(data);});
  child.start();
//////////////////////////////////////////////////////////////////////////////////////////////////Child.js
console.log("Hello World");
/////////////////////////////////////////////////////////////////////////////////////////////////////////
 result:
./log file was not created.
./out file was created but remain empty
./err file was created but remain empty
on the console of Main.js nothing is printed

so where can I found the log of Child.js???

**Comment by indexzero** [comment]
it's likely that your child is not writing any logs if those files are getting created.

**Comment by fithwith** [comment]
as you can see in the code, the child is writing console.log("Hello World"); 

so from where do you think that the problem come?

and why the issue was closed the problem is not resolved !!!!
