### ISSUE TITLE
Running a script with harmony flag

### ISSUE THREAD

**Issue by DominicTobias** [foreverjs/forever-monitor#103]
Hi, I tried adding `args: ['harmony']` but this had no effect, I found that to get a node script to run with the harmony flag I had to modify `command`:

	var child = new (forever.Monitor)(this.options.filePath, {
		sourceDir: this.options.basePath,
		watchDirectory: this.options.basePath,
		command: 'node --harmony'
	});

Am I missing something here? This feels a bit hacky..

**Comment by indexzero** [comment]
Nope. That's correct.
