### ISSUE TITLE
Winston colorized log support

### ISSUE THREAD

**Issue by adamcohen** [foreverjs/forever-monitor#104]
I'm using `forever-monitor` in an iojs v2.2.1 project with [Winston 1.0.0 ](https://github.com/winstonjs/winston) for logging.  My logs are colorized if I start my main `index.js` module directly, but once I start it through `forever-monitor`, I lose colorized output.  The only colored output is from the `forever-monitor` script itself, but once it loads the child process, the colorization disappears:

![screen shot 2015-07-30 at 1 45 57 pm 1](https://cloud.githubusercontent.com/assets/279925/8975451/f14079ac-36c1-11e5-978d-761cb0052949.png)

Here is my the code from `forever.js`

```javascript
require('dotenv').load()
var logger = require('./lib/app_logger')
var Monitor = require('forever-monitor').Monitor

var child = new Monitor('index.js', {
  watch: process.env.NODE_ENV === 'development',
  watchIgnorePatterns: ['*.log', 'coverage/**', '.git/**'],
  watchDirectory: '.'
})

child.on('watch:restart', function (info) {
  logger.info(`[Forever] Restarting script because ${info.file} changed`)
})

child.on('restart', function () {
  logger.info('[Forever] Restarting script')
})

child.start()
```

Is it possible to get Winston colorized log support when running your child process through `forever-monitor`? Am I doing something wrong here?  Thanks

**Comment by soundslocke** [comment]
I ran into this problem today when upgrading from Winston 0.8.0 to 1.0.1. Console text colors on inner processes no longer appeared.

After a little guessing I discovered adding the flag ```--color``` to the end of the command fixed it and colorful log entries appeared again. Not sure what changed or why that works.

**Comment by adamcohen** [comment]
I've just confirmed that switching back to Winston 0.8.0 fixes the color issue.  However, I'm unable to get your fix to work.  Where are you adding the `--color` flag? At the end of which command?  I usually start my process via `node forever.js index.js`, I've tried adding `--color` to the end of that command, but it doesn't work.

**Comment by adamcohen** [comment]
I seem to have figured it out. If you add:

    args: ['--color']

to the child arguments when creating a new `forever.Monitor`, it enables colorized output.
