### ISSUE TITLE
Add option to set polling fallback on chokidar

### ISSUE THREAD

**Issue by diogogmt** [foreverjs/forever-monitor#109]
Chokidar has a long poll fallback that uses fs.watchFile instead of fs.events.

The main reason for the long poll fallback is that Virtual Box doesn't send file system change events generated by kqueue on OSX to the Virtual Machine.
That makes the watch feature of forever-monitor useless when sharing folders from the host (with sync_folders and NFS) since the kqueue fs change events are not signaled to the VM

* Virtual Box had a ticket about the issue: https://www.virtualbox.org/ticket/10660
* There is also an issue on chokidar tracking the problem: https://github.com/paulmillr/chokidar/issues/242

**Comment by indexzero** [comment]
Fixed in #110
