### ISSUE TITLE
Using deprecated version of minimatch, throwing warnings when installing forever

### ISSUE THREAD

**Issue by alextmeyer** [foreverjs/forever-monitor#130]
Receive the following warning when installing forever due to forever-monitor being required:
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

minimatch version needs updated: https://github.com/foreverjs/forever-monitor/blob/master/package.json#L26

Related issue was created against forever but it is being caused by version issue in this package: https://github.com/foreverjs/forever/issues/858

**Comment by indexzero** [comment]
Fixed in #127
