### ISSUE TITLE
upgrade utile to 0.3.0

### ISSUE THREAD

**Issue by advaittrivedi** [foreverjs/forever-monitor#172]
https://github.com/foreverjs/forever is already using utile to 0.3.0. 
forever-monitor is still using 0.2.1. 
utile 0.2.1 has security vulnerability, https://github.com/Dome9/policy_reports/issues/2.
Any plans to upgrade forever-monitor to utile 0.3.0?

**Comment by kibertoad** [comment]
Thanks for reporting! I'll take a look.
