### ISSUE TITLE
Take a signal or command while running a process to manually restart it.

### ISSUE THREAD

**Issue by Industrial** [foreverjs/forever-monitor#88]
Hi.

I've recently replaced nodemon with forever because nodemon's watch functionality has issues (it watches the node_modules dir even if you configure it correctly).

One of the great features of nodemon (for me) is the ability to type "rs<enter>" to manually restart the process. This is nice because it allows me to restart the server but skip re-initializing the whole grunt/gulp setup.

Is this possible to implement with Forever?

**Comment by CaleyD** [comment]
this seems like a feature of a higher-level abstraction rather than forever-monitor module. You can achieve this pragmatically with forever-monitor by calling the .kill() method.
