### ISSUE TITLE
Attach monitor to script, but don't start it

### ISSUE THREAD

**Issue by ilanbiala** [foreverjs/forever-monitor#93]
How can I attach a forever monitor to a currently running forever script, but not start it when I programmatically create it so that the two don't conflict? Will they conflict?

**Comment by indexzero** [comment]
A `Monitor` instance cannot be attached to a currently running process. I'm not even sure if the Node.js core APIs would allow us to watch a currently running process we didn't exec ourselves.

**Comment by ilanbiala** [comment]
Maybe there's a better way. What I'm trying to do is restart my update script if a specific value is true, but to get the script running, I have to either `node script.js` or `forever script.js`...so is there a workaround?

**Comment by ilanbiala** [comment]
@indexzero any thoughts?

**Comment by indexzero** [comment]
@ilanbiala I'm not sure what you're trying to do. Can you give a fully working reproducible example?

**Comment by ilanbiala** [comment]
I have an update script that reloads the server. However, I cannot start the server via the script, so how can I attach a forever monitor to it through the script without any conflicts?

**Comment by indexzero** [comment]
I think I understand what your words are saying :smile: 

... but what I need is a full code example. Can you point me to a Github repository or Gist with code I can run?

**Comment by ilanbiala** [comment]
https://gist.github.com/ilanbiala/cc47a67a04988fdb8a28#file-gistfile1-js-L56, I want to restart the app server at that point, and if I detect a certain value, I need to also restart the update server in this Gist..

**Comment by indexzero** [comment]
Ok. Our suggestion is to write your `update.sh` script in node so that you can start your server with an instance of `forever.Monitor` to begin with :)

**Comment by ilanbiala** [comment]
Oh `update.sh` just calls some CLI things like `npm install` and `gulp build`. I have a script currently called `server.js` that is my app server, so you are saying to start that server through the Gist server and keep a reference in the Gist server? The issue then is that if I update the Gist code, how do I restart the update server in the Gist so that the new code is running in production?
