### ISSUE TITLE
forever-monitor in meteor

### ISSUE THREAD

**Issue by nor-bu** [foreverjs/forever-monitor#94]
hey,

i want to start a bundled meteor app from a other meteor app, when i cal forever monitor i becoming the error 'Not a Meteor app directory', from the app that i will start.

```
var runCell = new (forever.Monitor)('main.js',{
  'max':3,
  'silent':true,
  'sourceDir': '/path/to/main.js',
  'env':{
    'ROOT_URL':'http://127.0.0.1',
    'MONGO_URL':'mongodb://xyz.com',
    'PORT':4000
  }
});

runCell.on('exit', function(code){
  console.log(code);
});

runCell.on('stdout', function(data) {
  console.log('stdout: ' + data);
});

runCell.on('stderr', function(data) {
  console.log('stdout: ' + data);
});

runCell.start();
```

how can i fix this? thank's for help

**Comment by indexzero** [comment]
Not sure. I don't know much about meteor. Probably has something to the relative directory you are trying to startup in.

**Comment by norbu89** [comment]
thanks for answer, yes i think so too, but the problem is it works fine when i start the meteor app with the cli. i don't understand how can i set the right directory for meteor.

**Comment by indexzero** [comment]
Oh I see. You need to specify the `command` you are running.
